@startuml Juego
scale 1.5
' Pagina de plantuml: https://plantuml.com/es/class-diagram
'scale 1.5 | scale 200 width | scale 100 height | scale [max] 200x100
main --> juego
main --> constantes
camara --> constantes
interfaz_grafica --> constantes
inventario --> objecto
inventario --> constantes

class __main{
    + main()
}

class camara{
    + int ancho_pantalla
    + int alto_pantalla
    + __init__()
    + actualizar(objetivo_x, objetivo_y)
    + aplicar(x: Coordenada X, y: Coordenada Y) : Int
}

class constantes <<constantes>>{
    + int ANCHO
    + int ALTO
    + int TAMANIO_BLOQUE
    + int FPS
    + int FILAS
    + int COLUMNAS
    + set COLOR_FONDO
    + FUENTE
    + int GRAVEDAD
    + int FUERZA_SALTO
    + int VELOCIDAD_PERSONAJE
    + diccionario COLORES
    + TEXTURA_TIERRA
    + TEXTURA_PIEDRA
    + TEXTURA_PASTO
    + BLOQUES_SOLIDOS
    + diccionario HERRAMIENTAS
    + list CATEGORIAS
}

class interfaz_grafica{
    + __init__(mundo: Mundo)
    + dibujar()
}

class inventario{
    + __init__()
    + agregar_objeto(objeto)
    + obtener_item_actual() : objeto or None
    + dibujar(pantalla, fuente)
    - _dibujar_categorias(pantalla, fuente)
    - _dibujar_item(pantalla, fuente, item, y_pos, index)
    + seleccionar_barra_rapida(indice)
    - _dibujar_barra_rapida(pantalla, fuente)
    + manejar_evento(evento)
    + soltar_item_seleccionado()
}

class juego{}

class mapa{}

class mundo{}

class objeto{}

class personaje{}

class suelo{}

class utilidades{}

@enduml