@startuml DiagramaComponente
skinparam componentStyle rectangle
skinparam linetype ortho
skinparam shadowing true
skinparam arrowColor DarkSlateGray
skinparam ArrowFontSize 14
skinparam ArrowFontColor #222266

package "Componentes de Personaje" {
    [ComponenteMover]
    [ComponenteAnimacion]
    [ComponenteInventario]
    [ComponenteDisparo]
}

package "Entidades" {
    [PersonajeJugador]
    [Objeto]
    [Suelo]
    [Proyectil]
}

package "Infraestructura" {
    [Mundo]
    [ManjeadorChunks]
    [Mapa]
    [GestorDB]
    [Constantes]
    [Camara]
}

[Main]
[PresentadorJuego]
[VistaJuego]
[Inventario]
[Pygame]

Main --> PresentadorJuego : inicia
PresentadorJuego --> Mundo : controla lógica
PresentadorJuego --> VistaJuego : ordena dibujar
VistaJuego --> Camara : usa para desplazamiento
VistaJuego --> Constantes : usa configuración
VistaJuego ..> Pygame : renderiza
VistaJuego --> Inventario : dibuja
VistaJuego --> PersonajeJugador : dibuja
VistaJuego --> Objeto : dibuja
VistaJuego --> Suelo : dibuja

Mundo --> ManjeadorChunks : gestiona chunks
Mundo --> Mapa : genera terreno
Mundo --> PersonajeJugador : contiene
Mundo --> GestorDB : persistencia

ManjeadorChunks --> Mapa : obtiene terreno
ManjeadorChunks --> Suelo : instancia bloques
ManjeadorChunks --> Objeto : instancia objetos

PersonajeJugador --> Inventario : tiene
PersonajeJugador --> Camara : usa para posición
PersonajeJugador ..> Pygame : entrada usuario

Inventario --> Objeto : contiene items

GestorDB ..> sqlite3 : persistencia
GestorDB ..> os : rutas

Objeto ..> Pygame : imágenes, hitbox

PersonajeJugador --> ComponenteMover : usa
PersonajeJugador --> ComponenteAnimacion : usa
PersonajeJugador --> ComponenteInventario : usa
PersonajeJugador --> ComponenteDisparo : usa

ComponenteMover ..> PersonajeJugador : modifica movimiento
ComponenteAnimacion ..> PersonajeJugador : modifica animación
ComponenteInventario ..> Inventario : controla inventario
ComponenteDisparo ..> PersonajeJugador : permite disparar
ComponenteDisparo --> Proyectil : crea
Proyectil ..> Objeto : hereda

Pygame ..> Main
Pygame ..> VistaJuego
Pygame ..> Objeto
Pygame ..> PersonajeJugador

@enduml
