@startuml DiagramaComponente
[Juego]
[Camara]
[Interfaz_Grafica]
[Inventario]
[Mapa]
[Mundo]
[Personaje]
[Pygame]
[Mundo]
Jugador --(0-- Juego : computadora
Juego  <--> Mundo: actualizar_eventos
Interfaz_Grafica --> Juego: dibuja
Pygame --> Interfaz_Grafica: metodos
Camara <-- Mundo: requiere
Personaje <--> Mundo: actualiza_estado
Mundo <-- Mapa: cambia
Inventario <-- Personaje: cambia
@enduml
