@startuml DiagrmaSecuencia
actor usuario
participant Main
participant Juego
participant Mundo

activate usuario

usuario -> Main : main()
activate Main
activate Juego

Main -> Juego : manejar_eventos()
||15||
Main <-- Juego: eventos
||15||
Main -> Juego : Actualizar(dt, eventos)
Juego-> Mundo : Actualizar(dt, eventos)
activate Mundo
||15||
Main -> Juego : Dibujar()
Juego -> Graficos : Dibujar()
activate Graficos
||15||



@enduml